name: Deploy Bookiddo
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Install Surge.sh
        run: npm install -g surge

      - name: Deploy to Surge.sh
        run: surge ./build --token ${{ secrets.SURGE_TOKEN }} --domain https://${{ secrets.SURGE_DOMAIN }}.surge.sh